[network]
layer_span_details = [[[6,1,1], [1,1,1]], [[3,2,1], [1,1,1]], [[1,3,2], [1,2,1]], [[1,2,3], [1,1,2]], [[1,2,3], [1,1,2]], [[1,3,2], [1,2,1]]]
# We are also going to need to make sure layer sizes are consistent with the span details above, this means rewriting default config
layer_sizes = [2352, 756, 351, 156, 66, 25, 8]